#! /usr/bin/env python3
# coding utf-8

import requests

from grandPyBotApp.api_wikiMedia import ApiWikiMedia

openclassrooms = ApiWikiMedia("Paris")


def test_ApiWikipedia(monkeypatch):
    results = {'batchcomplete': '', 'query': {'pages': {'681159': {'pageid': 681159, 'ns': 0, 'title': 'Paris', 'extract': """Paris (/pa.ʁi/) est la commune la plus peuplée et la capitale de la France.\nElle se situe au cœur d'un vaste bassin sédimentaire aux sols fertiles et au climat tempéré, le bassin parisien, sur une boucle de 
la Seine, entre les confluents de celle-ci avec la Marne et l'Oise. Paris est également le chef-lieu de la région Île-de-France et le centre de la métropole du Grand Paris, créée en 2016. Elle est divisée en arrondissements, comme les villes de Lyon et de Marseille, au nombre de vingt. Administrativement, la ville constitue depuis le 1er janvier 2019 une collectivité à statut particulier nommée « Ville de Paris » (auparavant, elle était à la fois une commune et un département). L'État y dispose de prérogatives particulières exercées par le préfet de police de Paris. La ville a connu de profondes transformations sous le Second Empire dans les décennies 1850 et 1860 à travers d'importants travaux consistant notamment au percement de larges avenues, places et jardins et la construction de nombreux édifices, dirigés par le baron Haussmann, donnant à l'ancien Paris médiéval le visage qu'on lui connait de nos jours. \nLa ville de Paris comptait 2,187 millions d'habitants au 1er janvier 2020. Ses habitants sont appelés Parisiens. L'agglomération parisienne s’est largement développée au cours du XXe siècle, rassemblant 10,73 millions d'habitants au 1er janvier 2020, et son aire urbaine (l'agglomération et la couronne périurbaine) comptait 12,78 millions d'habitants. L'agglomération parisienne est ainsi la plus peuplée de France, elle est la troisième du continent européen et la 32e plus peuplée du monde au 1er janvier 2019.\nLa position de Lutèce, sur l'île aujourd'hui nommée l'île de la Cité, permettant le franchissement du grand fleuve navigable qu'est la Seine par une 
voie reliant le Nord et le Sud des Gaules, en fait dès l'Antiquité une cité importante, capitale des Parisii, puis lieu de séjour d'un empereur romain. Sa position au centre du territoire contrôlé par les rois francs la fait choisir comme capitale de la France à la place de Tournai. Située au cœur d'un territoire agricole fertile avec un climat humide et doux, Paris devient une des principales villes de France au cours du Xe siècle, avec des palais royaux, de riches abbayes et une cathédrale. Au cours du XIIe siècle, avec l'université de Paris, la cité devient un des premiers foyers en Europe pour l’enseignement et les arts. Le 
pouvoir royal se fixant dans cette ville, son importance économique et politique ne cesse de croître. Ainsi, au début du XIVe siècle, Paris est l'une des villes les plus importantes du monde chrétien. Au XVIIe siècle, elle est la capitale de la principale puissance politique européenne ; au XVIIIe siècle, l'un des plus grands centres culturels de l’Europe ; et au XIXe siècle, la capitale des arts et des plaisirs. Du XVIe siècle au XXe siècle, Paris a été la capitale de l'Empire colonial français. De 1804 à 1814 elle fut la capitale de l'Empire napoléonien qui couvrait une grande partie de l'Europe. Paris joue donc un rôle de tout premier plan dans l'histoire de l'Europe et du monde depuis des siècles.\nParis symbolise la culture française. En 2017 elle est classée comme étant la ville la plus élégante au monde. Surnommée la Ville Lumière, elle abrite des monuments mondialement connus comme la cathédrale Notre-Dame de Paris, la Tour Eiffel ou encore l'Arc de Triomphe en haut de l'avenue des Champs-Élysées, et elle est l'une des villes les plus visitées au monde. Son Musée du Louvre est le musée d'art le plus grand et le plus visité au monde. Paris est la capitale mondiale du luxe. Les premier et troisième groupes mondiaux ont leur siège à Paris. Parmi les marques de luxe les plus valorisées au monde les marques françaises sont les plus nombreuses et les trois premières sont parisiennes. Paris est la ville qui en 2018 compte le plus de palaces au monde. À Paris se déroule tous les ans la plus prestigieuse semaine internationale de la mode. C'est dans cette ville qu'ont exercé et qu'exercent des couturiers de renommée mondiale et plusieurs marques françaises du luxe sont connues internationalement. Dans le secteur de la haute gastronomie Paris est la ville qui compte le plus grand nombre de meilleures tables au monde. La capitale française n'est jumelée qu'avec une seule autre ville, Rome, ce qui est aussi valable dans l'autre sens, avec ce slogan « Seul Paris est digne de Rome, seule Rome est digne de Paris ».\nLa ville est, avec sa 
banlieue, la capitale économique de la France. Elle est la première place financière et boursière du pays. En 2017, le quartier d'affaires de La Défense est le plus grand d'Europe et le quatrième dans le monde en termes d'attractivité. Toujours en 2017, la région parisienne accueille plus d'institutions internationales et de sièges sociaux de très grandes entreprises que New York et que Londres. En 2018, elle est le siège de deux des dix plus grandes banques mondiales. Elle est également le siège d'organismes européens tels que l'Autorité européenne des marchés financiers, l'Autorité bancaire européenne ou l'Agence spatiale européenne et d'organismes internationaux tels que l'UNESCO, l'OCDE, l'ICC, le GAFI. La région parisienne est l'une des plus riches régions d'Europe. En 1989, elle a été désignée capitale européenne de la culture, et en 2017, capitale européenne de l'innovation. Paris est l'une des villes les plus chères au monde.\nLa densité de ses réseaux ferroviaires et autoroutiers et de ses structures aéroportuaires en font un point de convergence pour les transports nationaux et internationaux. Cette situation résulte d'une longue évolution, en particulier des conceptions centralisatrices des monarchies et des républiques, qui donnent un rôle 
considérable à la capitale dans le pays et tendent à y concentrer les institutions. Depuis les années 1980, les politiques publiques favorisent cependant la décentralisation. La macrocéphalie dont est atteinte la ville se concrétise par la convergence de la plupart des réseaux routiers et ferroviaires du pays en son 
centre et des écarts démographiques et économiques disproportionnés entre la capitale et la province : près de 19 % de la population française vit dans l'aire 
urbaine de Paris.\nLe club de football du Paris Saint-Germain et celui de rugby à XV du Stade français sont basés à Paris. Le Stade de France, enceinte de 80 000 places construite pour la Coupe du monde de football 1998, est situé au nord de la capitale, dans la commune voisine de Saint-Denis. Paris, qui accueille chaque année le tournoi du Grand Chelem de tennis de Roland Garros, a organisé les Jeux olympiques en 1900 puis en 1924 et deviendra en 2024 la deuxième ville avec Londres à les avoir accueillis trois fois. C'est à Paris que se déroulent tous les ans deux des plus prestigieuses courses hippiques au monde. Paris accueille également de nombreuses compétitions internationales et — depuis 1975 — l'arrivée du Tour de France, troisième événement sportif le plus suivi au monde."""}}}}
    def mockApiWikipedia():
        return results

    monkeypatch.setattr(requests, 'get', mockApiWikipedia)
    assert openclassrooms.content == results
    assert openclassrooms.city == "Paris"
    assert openclassrooms.url == "https://fr.wikipedia.org/w/api.php?format=json&action=query&prop=extracts&exintro=&explaintext=&titles=Paris"
    assert openclassrooms.history == """Paris (/pa', 'ʁi/) est la commune la plus peuplée et la capitale de la France', "\nElle se situe au cœur d'un vaste bassin sédimentaire aux sols fertiles et au climat tempéré, le bassin parisien, sur une boucle de la Seine, entre les confluents de celle-ci avec la Marne et l'Oise"""